spring.application.name=e-commerece-app
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=e-com;trustServerCertificate=true;integratedSecurity=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
security.jwt.issuer=SpringSecurityExample
security.jwt.expiry-time-in-seconds=86400
security.jwt.secret-key=${JWT_SECRET_KEY:FSmFQ0tNPt79eHKSiuaxu0Kwtie6El27XyVCPwTvlFU}
